### ISSUE TITLE
AssertGroup depends on object state

### ISSUE THREAD

**Issue by veelenga** [slvnperron/NUnit-GroupAssert#2]
As group assertion uses delayed evaluation, it does not work with mutable objects:

``` C#
    class Sample
    {
        public class Obj
        {
            public int Value { get; set; }

            public Obj(int Value)
            {
                this.Value = Value;
            }

            public override bool Equals(System.Object o)
            {
                if (o is Obj)
                {
                    return (o as Obj).Value == this.Value;
                }
                return false;
            }

        }

        [Test]
        public void test()
        {
            var group = new AssertGroup();

            Obj o1 = new Obj(10);
            Obj o2 = new Obj(11);

            Console.WriteLine(o1.Equals(o2)); // false

            group.Add(() => Assert.AreEqual(o1, o2)); // this does not fail test!!!!

            o2.Value = o1.Value;

            Console.WriteLine(o1.Equals(o2)); // true

            group.Verify();
        }
    }
```

Test passed.
And if you comment mutation, test will fail:

``` C#
 // o2.Value = o1.Value;
```

Do I expect something wrong ? Thanks

**Comment by slvnperron** [comment]
@veelenga This is on purpose. Execution only happens at Verify call. What else would you expect?
Thanks

**Comment by veelenga** [comment]
Oh, I got it. Thanks.

You wrote in description that NUnit-GroupAssert is similar to AssertJ's Soft Assertions. But there is no delayed evaluation and I was expected the same behavior. 

Actually, as for me this is a restriction. Seems it's easy to change it to work in way AssertJ works: execution can happen at the Add() call and Verify() will just add description.

**Comment by slvnperron** [comment]
Oh, well in that case it's true that the description is misleading. Do not hesitate to amend it and make a Pull Request. Thanks!
